apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://docker.for.mac.host.internal:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: Loki
    type: loki
    url: http://docker.for.mac.host.internal:3100
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://docker.for.mac.host.internal:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
