receivers:
  otlp:
    protocols:
      http:
        endpoint: 'localhost:4318'
processors:
  batch:
exporters:
  otlp:
    endpoint: 'localhost:3200'
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
