global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'catalogService'
    static_configs:
      - targets: ['docker.for.mac.host.internal:7001']
    scrape_interval: 10s
  # - job_name: 'nodeexporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['nodeexporter:9100']
  # - job_name: 'prometheus'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['localhost:9090']
  # - job_name: 'tempo'
  #   static_configs:
  #     - targets: ['localhost:3200']
