version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
  redis:
    container_name: catalogService-redis
    image: redis:latest
  mongo:
    container_name: catalogService-mongo
    image: mongo:latest
  mongo1:
    container_name: catalogService-mongo1
    image: mongo:latest
  mongo2:
    container_name: catalogService-mongo2
    image: mongo:latest
  app:
    container_name: catalogService
    depends_on:
      - mongo
      - redis
  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    depends_on:
      - zookeeper
  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
  connect:
    image: cnfldemos/cp-server-connect-datagen:0.6.0-7.3.0
    hostname: connect
    container_name: connect
    depends_on:
      - broker
      - schema-registry
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
      - schema-registry
      - connect
      - ksqldb-server
  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.3.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
      - connect
  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:7.3.0
    container_name: ksqldb-cli
    depends_on:
      - broker
      - connect
      - ksqldb-server
  ksql-datagen:
    image: confluentinc/ksqldb-examples:7.3.0
    hostname: ksql-datagen
    container_name: ksql-datagen
    depends_on:
      - ksqldb-server
      - broker
      - schema-registry
      - connect
  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.3.0
    depends_on:
      - broker
      - schema-registry
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
  loki:
    image: grafana/loki:latest
    container_name: loki
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
  jaeger:
    image: jaegertracing/all-in-one:latest